server:
  port: 8043

logging:
  level:
    org:
      springframework:
        web: INFO
        security: INFO
    vrs.rental_ms.integration: DEBUG

spring:
  application:
    name: rental_ms
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER:root}:${MONGODB_PASSWORD:root}@${MONGODB_HOST:vrs-rental-mongo}:${MONGODB_PORT:27017}/${MONGODB_NAME:vrs_rental}?authSource=admin
  rabbitmq:
    host: ${RABBITMQ_HOST:vrs-rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  output:
    ansi:
      enabled: always

management:
  server:
    port: 8043
  health:
    defaults:
      enabled: true
  endpoint:
    health:
      show-details: always
      group:
        readiness:
          include: "readinessState,mongo"
      mongo:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics

rental-ms:
  integration:
    security-auth-client:
      service-id: ${RENTAL_SERVICE_ID:rental-ms@vrs.com}
      service-secret: ${RENTAL_SERVICE_SECRET:vrs-rental-ms@rental_secret}
      base-url: ${SECURITY_BASE_URL:http://vrs-security:80}
      validate-token: /auth/validate
      generate-token-service: /auth/login/service
    security-client:
      base-url: ${SECURITY_BASE_URL:http://vrs-security:80}
      find-user-by-id: /users/{userId}
      find-user-address-by-id: /users/{userId}/addresses/{addressId}
    vehicle-client:
      base-url: ${VEHICLE_BASE_URL:http://vrs-vehicle:80}
      find-vehicle-by-id: /vehicles/{vehicleId}
      update-vehicle-status-by-id: /vehicles/{id}/status/{vehicleStatus}
      update-vehicle-rental-data: /vehicles/{id}/rental-data
    payment-client:
      base-url: ${PAYMENT_BASE_URL:http://localhost:9999}
      pay-rental: /transactions
      refund-rental: /transactions/{transactionId}/refund
  aws:
    s3:
      accessKey: ${AWS_ACCESS_KEY_ID:myKey}
      secretKey: ${AWS_SECRET_ACCESS_KEY:mykey}
      region: ${AWS_REGION:us-west-2}
      auto: false
      endpoint: http://vrs-localstack-service:4566
      bucketName: rentals-bucket
      exposureEndpoint: http://s3.vrs.cloud
  payment:
    api-key: ${PAYMENT_API_KEY:my-api-key}
    allowed-payment-method: credit_card
    allowed-installments: 1
    late-fee-multiplier: 1.20
